### ISSUE TITLE
Request: Enable "Create From Template" when nothing is selected

### ISSUE THREAD

**Issue by timstringer** [ksalzke/templates-for-omnifocus#1]
It would be helpful if the plug-in were enabled whether or not anything is selected in OmniFocus. The plug-in would simply display a list of available templates based on the contents of the Templates folder, ignoring any selection.

Thanks for a great plug-in!

**Comment by ksalzke** [comment]
Hi @timstringer! This is something I have struggled with a bit. I have an overabundance of Omni Automation actions and, on iOS/iPadOS, anything that is enabled when items are selected is shown when the share menu is invoked. I'd love to see this be customisable on the Omni end of things. In the meantime requiring that nothing be selected is my workaround...

That said, I can see the potential benefit! I think I'm going to (eventually) tweak my plugins to have a preferences setting that will allow each user to determine what works best for them: I've set up a pull request that I think allows this to happen but I need to test it a little more and add some documentation before I merge into the master code! :-) Thanks for the push to play with this!

**Comment by timstringer** [comment]
Thanks for your detailed comments, Kaitlin! I typically use the Console menu to launch plug-ins on the iPhone and iPad. I find it's more convenient than Share, especially when there's a sizeable list of plug-ins. In any case, adding a preference sounds like a good option. By default, I recommend that "Create From Template" be available regardless of what's selected.
