### ISSUE TITLE
Enhancement: Add option to be taken to newly created project

### ISSUE THREAD

**Issue by ksalzke** [ksalzke/templates-for-omnifocus#12]
Proposed by @timstringer:

> It would be helpful to have the option to be taken to the newly created project. When I created projects based on a template, I sometimes needs to make a few adjustments to line it up with the actual project and being dropped right into the new project would add a layer of convenience.

Considering adding this as a preference with three options:
* Always take to project after creating
* Never take to project after creating
* Always ask whether to go to project after creating

**Comment by timstringer** [comment]
Thanks for considering this addition, Kaitlin. Great idea to add a preference.

**Comment by ksalzke** [comment]
A checkbox has been added to 'go to project' but on rereading my old notes here I think it would still be good to include a preference for whether this should be selected by default.

**Comment by timstringer** [comment]
Thanks for adding the 'go to project' checkbox, Kaitlin. That's very helpful!

It would be great to have the option of having this checked by default. In most cases, I would want to go to the new project to make any adjustments that are specific to that project that aren't taken into account in the template.

**Comment by ksalzke** [comment]
Now added!

**Comment by timstringer** [comment]
Wonderful! Thanks, Kaitlin!
