### ISSUE TITLE
Plug-in stops when 'Top Level' destination is selected

### ISSUE THREAD

**Issue by Ben-Hampson** [ksalzke/templates-for-omnifocus#19]
Kaitlin, thank you for this plugin! I used Curt's for a long time and I wanted something that I could use on both my Mac and iOS devices. This plug-in is fantastic.

I only have one issue: on both my Mac and iPhone, if I select the 'Top Level' as the destination, when I press 'Continue' the plug-in stops. I have tried different templates but the same thing occurs. Is this a known issue? Or an unintended use case?

If there's a way for me to capture logs and share them, I'd be happy to do that.

**Comment by ksalzke** [comment]
Hi @Ben-Hampson. I've noticed this too in my most recent testing! I've clearly broken it somewhere along the way--it's on my list to review and fix ASAP!

**Comment by ksalzke** [comment]
@Ben-Hampson Should hopefully be fixed now! Sorry for the inconvenience - let me know if you run into any other issues. 🙂

**Comment by Ben-Hampson** [comment]
@ksalzke Thank you! It now creates a copy of the template project in the top level! 

However, after choosing the 'Top Level', it just duplicates the project and doesn't ask about what I want to fill in the placeholders with. Is this happening for you too? I'm seeing this on both my Mac and iPhone.

Also, on my iPhone I'm no longer seeing the 'Create a Template' option in the share sheet. 'Go To Templates Folder' and 'Hide Templates Folder' are there though. I tried reinstalling the plugin but it didn't work. I'm using the 'OmniFocus on iCloud Drive' location.

**Comment by ksalzke** [comment]
Oops! Clearly I didn't test with a project that had placeholders! That should be fixed now. Thanks for letting me know. :-) 

Is it possible you have the 'always enable' preference deselected on the iPhone? In that case the 'Create From Template' option won't show in the share sheet (by design, for those of us with three million plugins so as to limit the 'share' menu to plugins that refer to a particular selection). Is it available in the Automation menu when nothing is selected?

**Comment by Ben-Hampson** [comment]
This now works nicely on my Mac and iPhone! Thank you very much for your quick fixes.

With the issue of 'Create Template' not showing in the share sheet, I can't seem to figure it out. It's not a problem for me because I'm using a Shortcut to open the script URL, thanks to the [Script URL plugin](https://www.omni-automation.com/omnifocus/plug-in-script-url-for-plug-in.html). 

In case you want to pin this down further, here's what I know:
- When I access the share sheet from inside a project, I see the 'Go To Templates Folder' and 'Hide Templates Folder' actions. 'Create a Template' and 'Preferences' aren't there. 'Script URL for Plug-In' from the other plugin is also there. The missing 2 actions aren't in 'Edit Actions...' either.
- If I open a task and then access the share sheet, the situation is the same.
- I can't find a way to access the 'Preferences' action at all on the iPhone. So I don't think I could have disabled 'Always enable'. But I also don't have a way to check.
- I'm using 'OmniFocus in iCloud Drive'. I don't think the Preferences carry across from Mac to iPhone, but I see that on the Mac 'Always enable' is turned on.

Anyway, it's not an issue for me. But there's the info in case you need it. Thanks again!
