### ISSUE TITLE
Placeholder(s) and Dates Not Applied if Project is Selected

### ISSUE THREAD

**Issue by timstringer** [ksalzke/templates-for-omnifocus#3]
I notice that if I select a project as the destination, the actions are added to the project (albeit without the project name) and I'm not prompted for the placeholder(s) and date.

Consider either only allowing folders to be selected as a destination or creating an action group within a selected project with the placeholder(s) and dates applied.

Thanks!

**Comment by timstringer** [comment]
Another thought. If a project within the Templates folder is selected, consider using this project/template, bypassing the "Choose Template" dialog. If anything else is select (e.g. a project in another folder), I think it makes most sense to ignore the selection.

**Comment by ksalzke** [comment]
Hi @timstringer! I'm afraid you caught this plugin very much in a work-in-progress state!

I _think_ I've fixed this issue now (an action group is created and you should be prompted properly), along with a couple of others. _Hopefully_ I haven't introduced too many new bugs in the meantime but let me know how you get on.

(I've split the second comment out into its own issue but I think that's a sensible suggestion.)

**Comment by timstringer** [comment]
Thanks for the recent enhancement to the plug-in, @ksalzke!

I did some testing earlier today and everything worked as expected. In addition to being able to create an action group within an existing project, it's handy to be able to save to the root folder, to be able to limit the list to folders and to be able to access this plug-in regardless of what is selected.

One other tweak to propose is to include the omnifocusjs package in the zip file instead of requiring that people manually add the extension to the folder. The read me file could live alongside this package so that it's readily accessible.

Thanks again!

**Comment by ksalzke** [comment]
That's great news, thanks for letting me know! 🙂 

I know where you're coming from, the only problem would be that it would require me to recreate it each time (and would mess with my own setup a bit, but that could be worked around). Not too problematic in theory but I will definitely forget!

I would, ultimately, like to set up some more automation around updates and potentially move to Typescript so perhaps that could happen as a part of that, but it's not on my immediate radar I'm afraid!

**Comment by timstringer** [comment]
Thanks for your comments, Kaitlin!

> I know where you're coming from, the only problem would be that it would require me to recreate it each time (and would mess with my own setup a bit, but that could be worked around). Not too problematic in theory but I will definitely forget!

Would it potentially work to have a folder within the repository with an omnifocusjs extension. I notice that [this is what Josh does](https://github.com/deaghean/omnifocus-plugins) and it seems to work well.

**Comment by ksalzke** [comment]
That would work well, actually! I should do this for all my plugins, so I've made a note (in OmniFocus of course!) but probably won't get to it for a while. Thanks for the idea!

**Comment by timstringer** [comment]
Thanks for your comment, Kaitlin…and great to hear that this would work well. Being able to download the zip file and open/move the plug-in would make installation quick and easy.
